services:
  # PostgreSQL database
  postgres:
    image: postgres:18.1-bookworm
    container_name: epam-postgres
    ports:
      - "5432:5432" #! vulnerability?
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - epampgdata:/var/lib/postgresql/
    restart: unless-stopped

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epam-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app/
    restart: unless-stopped

volumes:
  epampgdata:
